import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { suggestion_id } = body;

    if (!suggestion_id) {
      return NextResponse.json(
        { error: "Missing suggestion_id" },
        { status: 400 },
      );
    }

    // Get current user
    const authClient = await createClient();
    const {
      data: { user },
    } = await authClient.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const adminClient = createAdminClient();

    const { data: suggestionExists, error: selErr } = await adminClient
      .from("meal_suggestions")
      .select("id, vote_count")
      .eq("id", suggestion_id)
      .single();

    if (selErr)
      return NextResponse.json(
        { error: `Failed to fetch suggestion: ${selErr.message}` },
        { status: 500 },
      );

    if (!suggestionExists) {
      return NextResponse.json(
        { error: "Suggestion not found" },
        { status: 404 },
      );
    }

    // Insert vote (only suggestion_id and user_id - created_at auto-generated by DB)
    const { data: voteData, error: insertErr } = await adminClient
      .from("suggestion_votes")
      .insert([{ suggestion_id, user_id: user.id }])
      .select()
      .single();

    if (insertErr) {
      // Handle duplicate vote (unique constraint violation)
      const msg = String(insertErr.message || "").toLowerCase();
      if (
        msg.includes("duplicate") ||
        msg.includes("unique") ||
        insertErr.code === "23505"
      ) {
        return NextResponse.json(
          { error: "You have already voted on this suggestion" },
          { status: 409 },
        );
      }
      // Other insert errors
      return NextResponse.json(
        { error: `Failed to record vote: ${insertErr.message}` },
        { status: 500 },
      );
    }

    // Fetch updated suggestion (trigger should have auto-incremented vote_count)
    const { data: updatedSuggestion, error: fetchErr } = await adminClient
      .from("meal_suggestions")
      .select("id, vote_count")
      .eq("id", suggestion_id)
      .single();

    if (fetchErr) {
      return NextResponse.json(
        { error: `Failed to fetch updated suggestion: ${fetchErr.message}` },
        { status: 500 },
      );
    }

    return NextResponse.json(
      {
        message: "Vote recorded successfully",
        vote: voteData,
        suggestion: updatedSuggestion,
      },
      { status: 201 },
    );
  } catch (error: unknown) {
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : "An unknown error occurred",
      },
      { status: 500 },
    );
  }
}
